# Generated by Django 3.2.7 on 2022-01-14 18:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenderReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=16, max_digits=20, verbose_name='Latitude')),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('city', models.CharField(blank=True, max_length=300, null=True)),
                ('building', models.CharField(max_length=30)),
                ('streetNo', models.CharField(max_length=100)),
                ('flootUnit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.PositiveBigIntegerField()),
                ('image', models.ImageField(upload_to='Vehicle_Images/')),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('unique_id', models.CharField(default='1', max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WholeShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=100, null=True)),
                ('productType', models.CharField(blank=True, max_length=100, null=True)),
                ('productQuantity', models.PositiveIntegerField(blank=True, null=True)),
                ('productDescription', models.CharField(blank=True, max_length=600, null=True)),
                ('paymentMethod', models.CharField(choices=[('Cash', 'Cash'), ('Credit/Debit', 'Credit/Debit')], default='Cash', max_length=20)),
                ('distance', models.PositiveBigIntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('Shipment_Status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_whole_shipment', to='shipment.senderreceiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_whole_shipment', to='shipment.senderreceiver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.vehicles')),
            ],
        ),
    ]
