# Generated by Django 3.2.7 on 2022-01-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_auto_20220114_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholeshipment',
            name='Shipment_Status',
        ),
    ]
