# Generated by Django 3.2.7 on 2022-02-09 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_remove_wholeshipment_shipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='rate',
        ),
    ]
