# Generated by Django 3.2.7 on 2022-02-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_remove_vehicles_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
