# Generated by Django 3.2.7 on 2022-02-10 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_vehicles_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicles',
            name='rate',
        ),
    ]
