# Generated by Django 3.2.7 on 2022-03-15 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0006_remove_vehicles_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholeshipment',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
