# Generated by Django 3.2.7 on 2022-03-16 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipment', '0007_wholeshipment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholeshipment',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Assign_to_Driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
