# Generated by Django 3.2.7 on 2022-03-19 08:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_wholeshipment_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_all_status', to='shipment.wholeshipment')),
            ],
        ),
        migrations.AlterField(
            model_name='wholeshipment',
            name='status',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment.status'),
        ),
    ]
