# Generated by Django 3.2.7 on 2022-03-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0009_auto_20220319_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='shipment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_all_status', to='shipment.wholeshipment'),
        ),
    ]
