# Generated by Django 3.2.7 on 2022-03-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0011_alter_wholeshipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholeshipment',
            name='status',
        ),
        migrations.AddField(
            model_name='wholeshipment',
            name='status',
            field=models.ManyToManyField(blank=True, null=True, to='shipment.Status'),
        ),
    ]
