# Generated by Django 3.2.7 on 2022-03-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0012_auto_20220319_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholeshipment',
            name='status',
            field=models.ManyToManyField(blank=True, to='shipment.Status'),
        ),
    ]
