# Generated by Django 3.2.7 on 2022-03-19 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipment', '0013_alter_wholeshipment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wholeshipment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Customer_all_Shipment', to=settings.AUTH_USER_MODEL),
        ),
    ]
