# Generated by Django 3.2.7 on 2022-04-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0015_remove_wholeshipment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wholeshipment',
            name='time',
        ),
        migrations.AddField(
            model_name='wholeshipment',
            name='Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wholeshipment',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True, verbose_name='distance'),
        ),
    ]
