# Generated by Django 3.2.7 on 2022-04-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0016_auto_20220410_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholeshipment',
            name='totalCost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
