# Generated by Django 3.2.7 on 2022-04-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0017_wholeshipment_totalcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderreceiver',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='senderreceiver',
            name='phone',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wholeshipment',
            name='totalCost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
