# Generated by Django 3.2.7 on 2022-05-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0018_auto_20220416_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senderreceiver',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
