# Generated by Django 3.2.7 on 2022-01-14 18:30

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipment', '__first__'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, error_messages={'null': 'This feild cannot be nulll'}, max_length=255, null=True, unique=True, verbose_name='email')),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Company', 'Company'), ('Driver', 'Driver')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('owner_Name', models.CharField(blank=True, max_length=255)),
                ('coverage', models.JSONField(blank=True, null=True)),
                ('mailing_address', models.CharField(blank=True, max_length=1000)),
                ('allPakistan', models.BooleanField(default=False)),
                ('website', models.CharField(blank=True, max_length=500, null=True)),
                ('cnic', models.CharField(max_length=13)),
                ('cnic_front', models.ImageField(blank=True, null=True, upload_to='Cnic_front/')),
                ('cnic_back', models.ImageField(blank=True, null=True, upload_to='Cnic_back/')),
                ('Ntn_number', models.CharField(max_length=15)),
                ('Ntn_picture', models.ImageField(blank=True, null=True, upload_to='Ntn_Number/')),
                ('Registration_Certificate', models.ImageField(blank=True, null=True, upload_to='Registration_Certificate/')),
                ('is_Verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='Driver_profile/')),
                ('cnic_front', models.ImageField(blank=True, null=True, upload_to='Driver/Cnic_front/')),
                ('cnic_back', models.ImageField(blank=True, null=True, upload_to='Driver/Cnic_back/')),
                ('company', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_Driver', to=settings.AUTH_USER_MODEL)),
                ('vehicle_driver', models.ManyToManyField(to='shipment.Vehicles')),
            ],
        ),
        migrations.AddField(
            model_name='basicuser',
            name='company',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='driver',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.driver'),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
