# Generated by Django 3.2.7 on 2022-01-25 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_driver_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Company_Driver', to=settings.AUTH_USER_MODEL),
        ),
    ]
