# Generated by Django 3.2.7 on 2022-01-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_driver_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, error_messages={'Wrong': 'Pull right url of website'}, null=True),
        ),
    ]
