# Generated by Django 3.2.7 on 2022-02-09 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_remove_vehicles_rate'),
        ('accounts', '0004_alter_company_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('registration_city', models.CharField(max_length=255)),
                ('rate', models.IntegerField()),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Company_Vehicles', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shipment.vehicles')),
            ],
        ),
    ]
