# Generated by Django 3.2.7 on 2022-02-09 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company_vehicles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_vehicles',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='All_Vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
