# Generated by Django 3.2.7 on 2022-02-10 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_vehicles_rate'),
        ('accounts', '0006_alter_company_vehicles_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_vehicles',
            name='rate',
        ),
        migrations.CreateModel(
            name='VehicelRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Vehicles_rate', to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shipment.vehicles')),
            ],
        ),
    ]
