# Generated by Django 3.2.7 on 2022-03-15 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20220210_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_isBusy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_onWork',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DriverTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=None, unique=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
