# Generated by Django 3.2.7 on 2022-03-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220315_1812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverTimeTable',
        ),
    ]
