# Generated by Django 3.2.7 on 2022-03-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_delete_drivertimetable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_Verified',
        ),
        migrations.AddField(
            model_name='basicuser',
            name='is_Verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basicuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
