# Generated by Django 3.2.7 on 2022-05-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220320_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuser',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='Customer_profile/'),
        ),
        migrations.AddField(
            model_name='company',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='Company_profile/'),
        ),
    ]
