# Generated by Django 3.2.7 on 2022-05-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220514_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicuser',
            name='number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
