# Generated by Django 3.2.7 on 2022-05-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_basicuser_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='License',
            field=models.ImageField(blank=True, null=True, upload_to='Driver/License/'),
        ),
    ]
