# Generated by Django 3.2.7 on 2022-05-25 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_company_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='cnic_back',
        ),
        migrations.RemoveField(
            model_name='company',
            name='cnic_front',
        ),
    ]
