# Generated by Django 3.2.7 on 2022-05-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220525_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_vehicles',
            name='Vehicle_Busy',
            field=models.BooleanField(default=False),
        ),
    ]
